const defaults = [
  ["", "Ghostty Default"],
  ["true", "On"],
  ["false", "Off"],
];
export const fields = [
  {
    key: "font-family",
    label: "Font Family",
    group: "appearance",
    type: "fonts",
    placeholder: "JetBrains Mono",
    help: "Separate fallback families with commas. Fonts must be installed for Ghostty; browser availability may differ.",
  },
  {
    key: "font-size",
    label: "Font Size",
    group: "appearance",
    type: "number",
    min: 1,
    max: 100,
    step: 0.5,
    placeholder: "Default",
    help: "Size in points. Leave empty to use the default.",
  },
  {
    key: "background-opacity",
    label: "Background Opacity",
    group: "appearance",
    type: "opacity",
    help: "Text stays opaque. macOS requires a full restart; native fullscreen ignores transparency.",
  },
  {
    key: "background-blur",
    label: "Background Blur",
    group: "appearance",
    options: [
      ["", "Ghostty Default"],
      ["false", "Off"],
      ["true", "On · Standard"],
      ["10", "Subtle · 10"],
      ["30", "Strong · 30"],
    ],
    help: "Requires transparency. Supported by macOS and some Linux desktops.",
  },
  {
    key: "window-padding-x",
    label: "Horizontal Padding",
    group: "appearance",
    type: "padding",
    placeholder: "Default",
    help: "Points. Use one value for both sides, or left,right.",
  },
  {
    key: "window-padding-y",
    label: "Vertical Padding",
    group: "appearance",
    type: "padding",
    placeholder: "Default",
    help: "Points. Use one value for both sides, or top,bottom. Padding changes apply to new terminals.",
  },
  {
    key: "window-padding-balance",
    label: "Balance Padding",
    group: "appearance",
    options: defaults,
    help: "Distributes leftover space around the terminal grid.",
  },
  {
    key: "minimum-contrast",
    label: "Minimum Text Contrast",
    group: "appearance",
    type: "number",
    min: 1,
    max: 21,
    step: 0.1,
    placeholder: "Default",
    help: "Adjusts text colors to meet this contrast ratio. Applies to both comparison previews.",
  },
  {
    key: "cursor-style",
    label: "Cursor Shape",
    group: "interaction",
    options: [
      ["", "Ghostty Default"],
      ["block", "Block"],
      ["bar", "Bar"],
      ["underline", "Underline"],
      ["block_hollow", "Hollow Block"],
    ],
    help: "Shell integration and running programs can override the cursor shape.",
  },
  {
    key: "cursor-style-blink",
    label: "Blinking Cursor",
    group: "interaction",
    options: defaults,
    help: "Sets the initial blink behavior. Applications may override it.",
  },
  {
    key: "mouse-hide-while-typing",
    label: "Hide Mouse While Typing",
    group: "interaction",
    options: defaults,
  },
  {
    key: "copy-on-select",
    label: "Copy Selected Text",
    group: "interaction",
    options: [
      ["", "Ghostty Default"],
      ["true", "Automatic"],
      ["clipboard", "System Clipboard"],
      ["false", "Off"],
    ],
    help: "Automatic prefers the selection clipboard where available. System clipboard also replaces your regular clipboard.",
  },
  {
    key: "scrollback-limit",
    label: "Scrollback Limit",
    group: "interaction",
    type: "number",
    min: 0,
    max: 4294967295,
    step: 1,
    placeholder: "Default",
    help: "Bytes per terminal, not lines. Example: 10000000 ≈ 10 MB. More history may use more memory.",
  },
  {
    key: "window-inherit-working-directory",
    label: "Inherit Working Directory",
    group: "interaction",
    options: defaults,
    help: "New windows start in the previously focused window’s directory.",
  },
  {
    key: "confirm-close-surface",
    label: "Confirm Before Closing",
    group: "interaction",
    options: [
      ["", "Ghostty Default"],
      ["true", "When a Process Is Running"],
      ["always", "Always"],
      ["false", "Never"],
    ],
    help: "“Never” can close a running process without a warning.",
  },
  {
    key: "macos-titlebar-style",
    label: "Titlebar & Tabs",
    group: "macos",
    options: [
      ["", "Ghostty Default"],
      ["native", "Native"],
      ["transparent", "Transparent"],
      ["tabs", "Integrated Tabs"],
      ["hidden", "Hidden"],
    ],
    help: "macOS only. Integrated tabs follow the terminal background. Hidden removes the tab bar; new tabs open as windows. Style changes apply to new windows.",
  },
  {
    key: "window-theme",
    label: "Window Appearance",
    group: "macos",
    options: [
      ["", "Ghostty Default"],
      ["auto", "Match Terminal"],
      ["system", "Match System"],
      ["light", "Light"],
      ["dark", "Dark"],
    ],
    help: "Controls the native titlebar. Transparent and integrated styles follow the terminal background on macOS regardless of this setting.",
  },
  {
    key: "window-title-font-family",
    label: "Title & Tab Font",
    group: "macos",
    type: "text",
    placeholder: "System Default",
    help: "One installed font family for window and tab titles. Also supported on Linux; browser availability may differ.",
  },
  {
    key: "macos-window-buttons",
    label: "Window Buttons",
    group: "macos",
    options: [
      ["", "Ghostty Default"],
      ["visible", "Visible"],
      ["hidden", "Hidden"],
    ],
    help: "Show or hide the macOS traffic lights. Changes apply to new windows; a hidden titlebar always hides them.",
  },
  {
    key: "macos-titlebar-proxy-icon",
    label: "Titlebar Folder Icon",
    group: "macos",
    options: [
      ["", "Ghostty Default"],
      ["visible", "Visible"],
      ["hidden", "Hidden"],
    ],
    help: "macOS native titlebar only. Updates after the working directory changes. Tab colors, height and corner shape are managed by macOS.",
  },
  {
    key: "macos-option-as-alt",
    label: "Option as Alt",
    group: "macos",
    options: [
      ["", "Ghostty Default"],
      ["true", "Both Option Keys"],
      ["left", "Left Option Only"],
      ["right", "Right Option Only"],
      ["false", "Keep Unicode Input"],
    ],
    help: "Enables terminal Alt shortcuts; that Option key can no longer type special characters the usual macOS way.",
  },
  {
    key: "quit-after-last-window-closed",
    label: "Quit After Last Window",
    group: "macos",
    options: defaults,
    help: "Also supported on Linux. macOS normally keeps the app running with no windows.",
  },
];
